# Dependencies
markdown:         kramdown
highlighter:         rouge

# Permalinks
permalink:        pretty

# Setup
title:            Anh Trinh
tagline:          'JavaScript Developer'
description:      'Hi everyone! Thanks for visiting my blog. I hope that you will find it useful. I am <a href="https://twitter.com/ptgamr" target="_blank">@ptgamr</a> on Twitter'
url:              http://trinhtrunganh.com

author:
  name:           'Anh Trinh'
  url:            https://twitter.com/ptgamr

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/ptgamr.github.io
